### ISSUE TITLE
openwhisk: actions invoked with the openwhisk client don't generate a trace anymore

### ISSUE THREAD

**Issue by tripodsan** [epsagon/epsagon-node#218]
An openwhisk action invoking another action using the openwhisk client used to generate a trace; but this no longer works.

epsagon version: 1.48.1

**Comment by tripodsan** [comment]
_I'll take a look_

**Comment by tripodsan** [comment]
it seems that [this commit](https://github.com/epsagon/epsagon-node/commit/3640fe5bca2fcb82132f5689958ec6e792a30406) broke the webpack support.

I see tons of:

```
2020-01-24T06:23:21.510Z       stdout: TypeError: __webpack_require__(...).resolve.paths is not a function
    at Object.e.exports.getModules (/nodejsAction/XXBLjNOn/main.js:9661:49196)
    at Object.e.exports.patchModule (/nodejsAction/XXBLjNOn/main.js:9661:49425)
    at Object.init (/nodejsAction/XXBLjNOn/main.js:9661:122508)
    at patch (/nodejsAction/XXBLjNOn/main.js:9661:133236)
    at Array.forEach (<anonymous>)
    at Object../node_modules/epsagon/dist/bundle.js (/nodejsAction/XXBLjNOn/main.js:9661:133461)
    at __webpack_require__ (/nodejsAction/XXBLjNOn/main.js:30:30)
    at /nodejsAction/XXBLjNOn/main.js:30919:36
    at /nodejsAction/XXBLjNOn/main.js:30901:20
```
