### ISSUE TITLE
http response handling changes of epsagon 1.58.3 still produce runtime errors when webpacked

### ISSUE THREAD

**Issue by tripodsan** [epsagon/epsagon-node#256]
with #249 fixed, the tests now work locally, but when bundling with webpack, they still fail:

```
RangeError: Resource length mismatch (possibly incomplete body)
    at throwLengthMismatch (/Users/tripod/codez/helix/epsagon-testing/action-with-fetch/dist/default/epsagon-testing@1.0.2-bundle.js:4726:11)
    at StreamResponse.validateIntegrity (/Users/tripod/codez/helix/epsagon-testing/action-with-fetch/dist/default/epsagon-testing@1.0.2-bundle.js:4876:13)
    at awaitBuffer.then.already_1.tap.buffer (/Users/tripod/codez/helix/epsagon-testing/action-with-fetch/dist/default/epsagon-testing@1.0.2-bundle.js:4790:52)
    at /Users/tripod/codez/helix/epsagon-testing/action-with-fetch/dist/default/epsagon-testing@1.0.2-bundle.js:1571:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

when running the test locally, I see that the arguments passed into the `internalHttpWrapper` are:

```
http arguments [Arguments] {
  '0':
   { createConnection: [Function: createConnection],
     agent: false,
     hostname: 'adobeioruntime.net',
     method: 'GET',
     path:
      '/api/v1/web/helix/helix-services/word2md@v1...',
     port: 443,
     protocol: 'https:',
     headers: { connection: 'keep-alive' },
     epsagonSkipResponseData: true } }
```

but when running in the bundle, i get:

```
http arguments [Arguments] {
  '0':
   { createConnection: [Function: createConnection],
     agent: false,
     hostname: 'adobeioruntime.net',
     method: 'GET',
     path:
      '/api/v1/web/helix/helix-services/word2md@v1...,
     port: 443,
     protocol: 'https:',
     headers: { connection: 'keep-alive' } } }
```

It seems that the shimmer can't patch the method when it's bundled.

**Comment by tripodsan** [comment]
the error is reproducible here:
https://github.com/tripodsan/epsagon-testing/tree/master/action-with-fetch

**Comment by tripodsan** [comment]
as a quick workaround...could we add a general config option to `DisableHttpResponseBodyCapture` ?
