### ISSUE TITLE
kafka send: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by solaris007** [epsagon/epsagon-node#284]
version: epagon-node 1.63.1

When using `kafkajs#send` espagon produces an uncaught "Maximum call stack size exceeded" error that breaks our openwhisk action sending the event.

Downgrading to version 1.62.3 fixeds the issue which was probably introduced via #277 

https://github.com/epsagon/epsagon-node/compare/v1.62.3...v1.63.1

There seems to be circularity between:
```js
        const patchedSend = messages => kafkaSendMiddleware(messages, producer);
        ...
        response = producer.originalSend(messages);
```
in https://github.com/epsagon/epsagon-node/blob/master/src/events/kafkajs.js

Above two lines are featured in the stack:
```
RangeError: Maximum call stack size exceeded
    at Object.addException (/code/dist/action/index.js:43842:15)
    at Object.setException (/code/dist/action/index.js:43493:16)
    at kafkaSendMiddleware (/code/dist/action/index.js:57588:19)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
    at kafkaSendMiddleware (/code/dist/action/index.js:57585:29)
    at Object.patchedSend (/code/dist/action/index.js:57702:41)
```

/cc @ekremney @ranrib @idonava

**Comment by solaris007** [comment]
@ranrib at the beginning it was not apparent that epsagon was at fault (just like in #271 ), only via time, debugger and bundling the latest dev version of epsagon was the fault detected. we deserve a beer :D
I suggest to introduce better error handling and logging.
