### ISSUE TITLE
Error when using a Winston logger in Epsagon instrumented code during Mocha test

### ISSUE THREAD

**Issue by jcollum** [epsagon/epsagon-node#404]
Working (no error) version of function: 

```
async function buildPayload(err, res, event) {
    if (err) {
        console.log({
            level: 'ERROR',
            message: 'Failed to query for data.',
            function: 'buildPayload',
            filename: __filename,
            error: err.toString()
        });
        return Promise.reject(err);
    }
...
}
```

Failing version: 

```
const {version, name}  = require ('../package.json');
const logger = winston.createLogger({
    level: process.env.LOG_LEVEL || 'warn',
    defaultMeta: {service: name, filename: __filename, version},
    transports: [
        new winston.transports.Console({
            format: winston.format.json()
        })
    ]
});
... 

async function buildPayload(err, res, event) {
    logger.debug("buildPayload starting"); 
...
}
```

In case it isn't clear, `...` means I left code out. Doesn't matter, if I put in the Winston logger in the epsagon-instrumented code it fails on the first line. Stack trace: 

```
TypeError: Cannot read property 'node' of undefined
    at Object.e.exports.createTracer (/Users/justin.collum/work/read-account-lambda/node_modules/epsagon/dist/bundle.js:1:28127)
    at Object.trace_object_get [as getTrace] (/Users/justin.collum/work/read-account-lambda/node_modules/epsagon/dist/bundle.js:1:37578)
    at Object.e.exports.getTraceId (/Users/justin.collum/work/read-account-lambda/node_modules/epsagon/dist/bundle.js:1:36832)
    at /Users/justin.collum/work/read-account-lambda/node_modules/epsagon/dist/bundle.js:1:151398
    at DerivedLogger.<anonymous> (/Users/justin.collum/work/read-account-lambda/node_modules/epsagon/dist/bundle.js:1:151416)
    at DerivedLogger.<computed> [as debug] (/Users/justin.collum/work/read-account-lambda/node_modules/winston/lib/winston/create-logger.js:81:14)
    at buildPayload (/Users/justin.collum/work/read-account-lambda/lib/read-account-lambda.js:89:16)
    at Context.<anonymous> (/Users/justin.collum/work/read-account-lambda/test/read-account-lambda-test.js:109:20)
    at callFn (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:535:10)
    at /Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:653:12
    at next (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:447:14)
    at /Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:457:7
    at next (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:362:14)
    at /Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:420:7
    at done (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runnable.js:334:5)
    at callFn (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runnable.js:410:7)
    at Hook.Runnable.run (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runnable.js:379:7)
    at next (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:384:10)
    at Immediate._onImmediate (/Users/justin.collum/work/read-account-lambda/node_modules/mocha/lib/runner.js:425:5)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

```

Relevant sections of package-lock: 

```
    "epsagon": {
      "version": "1.94.0",
      "resolved": "https://registry.npmjs.org/epsagon/-/epsagon-1.94.0.tgz",
      "integrity": "sha512-hObfsn1eYJRc+WJvbgOla8kma8oaxKDSjmb8rOkjqpGoLeUsuM/jhcdtnHFDlwl4DNumWxe3bAqaYIJHNTAEvw==",
      "requires": {
        "axios": "^0.19.0",
        "google-protobuf": "^3.5.0",
        "json.sortify": "^2.2.2",
        "md5": "^2.2.1",
        "require-in-the-middle": "^5.0.3",
        "shimmer": "^1.2.1",
        "uuid-parse": "^1.1.0",
        "uuid4": "^1.0.0"
      }
    },
```

```
 "winston": {
      "version": "3.3.3",
      "resolved": "https://registry.npmjs.org/winston/-/winston-3.3.3.tgz",
      "integrity": "sha512-oEXTISQnC8VlSAKf1KYSSd7J6IWuRPQqDdo8eoRNaYKLvwSb5+79Z3Yi1lrl6KDpU6/VWaxpakDAtb1oQ4n9aw==",
      "requires": {
        "@dabh/diagnostics": "^2.0.2",
        "async": "^3.1.0",
        "is-stream": "^2.0.0",
        "logform": "^2.2.0",
        "one-time": "^1.0.0",
        "readable-stream": "^3.4.0",
        "stack-trace": "0.0.x",
        "triple-beam": "^1.3.0",
        "winston-transport": "^4.4.0"
      },
      "dependencies": {
        "async": {
          "version": "3.2.0",
          "resolved": "https://registry.npmjs.org/async/-/async-3.2.0.tgz",
          "integrity": "sha512-TR2mEZFVOj2pLStYxLht7TyfuRzaydfpxr3k9RpHIzMgw7A64dzsdqCxH1WJyQdoe8T10nDXd9wnEigmiuHIZw=="
        }
      }
    },
```

package deps: 

```
"devDependencies": {
    "ajv": "^5.5.2",
    "aws-sdk-mock": "^5.0.0",
    "chai": "^4.2.0",
    "eslint": "^6.6.0",
    "mocha": "^6.2.2",
    "nyc": "^14.1.1",
    "rewire": "^4.0.1",
    "sinon": "^9.0.2"
  },
  "dependencies": { 
    "aws-sdk": "^2.784.0",
    "epsagon": "^1.94.0",
    "lodash": "^4.17.20",
    "winston": "~3.3.3"
  },

```

Env: 

```
Node v12.16.1
NPM 6.14.10
```

I'm running Mocha via IntelliJ IDEA usually but it also fails in the same way when running from command line.

**Comment by ranrib** [comment]
Thanks @jcollum, we'll investigate it

**Comment by ranrib** [comment]
But in general, for testing/local needs, we recommend setting `DISABLE_EPSAGON=TRUE` as an env var. This completely "shuts down" the tracing, which makes sure no side effects are happening in tests.

Can you kindly try that @jcollum?

**Comment by ranrib** [comment]
I tried to replicate it with the following example, but couldn't manage to do so. 
Can you kindly help me troubleshoot it? Also do you mind upgrading your epsagon version to the latest?

```
var assert = require('assert');
const winston = require('winston');
const epsagon = require('epsagon');

const logger = winston.createLogger({
    level: process.env.LOG_LEVEL || 'warn',
    defaultMeta: {service: 'test', filename: __filename, version: '1.0'},
    transports: [
        new winston.transports.Console({
            format: winston.format.json()
        })
    ]
});

const test = function buildPayload(err, res, event) {
    logger.debug("buildPayload starting"); 
}

describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
        test()
      assert.equal([1, 2, 3].indexOf(4), -1);
    });
  });
});
```

**Comment by jcollum** [comment]
I'll take a look on monday

**Comment by jcollum** [comment]
Updated to Epsagon@latest: 

```
    "epsagon": {
      "version": "1.103.1",
      "resolved": "https://registry.npmjs.org/epsagon/-/epsagon-1.103.1.tgz",
      "integrity": "sha512-t2wNILK1ilX7WjzNdgKiH9Tu9AYjxFDmG11a/e/MIIIwfr48Swl/UkoMGkT+xoqw7VNHUIHBqoOm+wR2WTMeUA==",
      "requires": {
        "axios": "^0.21.1",
        "google-protobuf": "^3.5.0",
        "json.sortify": "^2.2.2",
        "md5": "^2.2.1",
        "require-in-the-middle": "^5.0.3",
        "shimmer": "^1.2.1",
        "uuid-parse": "^1.1.0",
        "uuid4": "^1.0.0"
      },

```

Still seeing the same error.

Used `DISABLE_EPSAGON=TRUE` and the error about node property being undefined went away, so that works.  Tests aren't passing but it appears to be a different issue unrelated to Epsagon. These tests are overriding the `process` object (I didn't do it) so that's probably where the problem lies, I think that has all kinds of repercussions and odd side-effects.

**Comment by ranrib** [comment]
Yes, it's indeed the error with accessing `process.versions.node` - we can fix it to be more resilient and fail-safe. Would you like that?

**Comment by jcollum** [comment]
Nah, I think if a dev overwrites the process object it's their fault their
tests fail!
