### ISSUE TITLE
Build failing on Heroku

### ISSUE THREAD

**Issue by sks147** [epsagon/epsagon-node#495]
Dependencies versions

```json

"dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "epsagon-frameworks": "^1.30.0",
    "express": "^4.17.1",
    "mongodb": "^3.5.9",
    "nodemon": "^2.0.4",
},

```

It worked fine when building on local, I could see localhost metrics in the dashboard.
But it's faling when I'm pushing the latest code to heroku.
```bash
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/nodejs
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        USE_YARN_CACHE=true
remote:        NODE_OPTIONS=-r epsagon-frameworks
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  14.0.0
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:        
remote:        Resolving node version 14.0.0...
remote:        Downloading and installing node 14.0.0...
remote: internal/modules/cjs/loader.js:1017
remote:   throw err;
remote:   ^
remote: 
remote: Error: Cannot find module 'epsagon-frameworks'
remote: Require stack:
remote: - internal/preload
remote:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
remote:     at Function.Module._load (internal/modules/cjs/loader.js:884:27)
remote:     at Module.require (internal/modules/cjs/loader.js:1074:19)
remote:     at Module._preloadModules (internal/modules/cjs/loader.js:1330:12)
remote:     at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
remote:     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
remote:     at internal/main/run_main_module.js:7:1 {
remote:   code: 'MODULE_NOT_FOUND',
remote:   requireStack: [ 'internal/preload' ]
remote: }
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
```

**Comment by ranrib** [comment]
Hi @sks147, it looks like the package is missing in the heroku server. Can you confirm that epsagon-frameworks is available?
